# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('keyWords', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
